<div class="viewed d-none d-xl-block">
    <?$APPLICATION->IncludeComponent(
        "bitrix:catalog.products.viewed",
        ".default",
        array(
            "ACTION_VARIABLE" => "action_cpv",
            "ADDITIONAL_PICT_PROP_7" => "-",
            "ADDITIONAL_PICT_PROP_9" => "-",
            "ADD_PROPERTIES_TO_BASKET" => "Y",
            "ADD_TO_BASKET_ACTION" => "ADD",
            "BASKET_URL" => "/personal/basket.php",
            "CACHE_GROUPS" => "Y",
            "CACHE_TIME" => "3600",
            "CACHE_TYPE" => "A",
            "CART_PROPERTIES_7" => array(
                0 => "",
                1 => "",
            ),
            "CART_PROPERTIES_9" => array(
                0 => "",
                1 => "",
            ),
            "CONVERT_CURRENCY" => "N",
            "DEPTH" => "2",
            "DISPLAY_COMPARE" => "N",
            "ENLARGE_PRODUCT" => "STRICT",
            "HIDE_NOT_AVAILABLE" => "N",
            "HIDE_NOT_AVAILABLE_OFFERS" => "N",
            "IBLOCK_ID" => IBLOCK_ID__CATALOG,
            "IBLOCK_MODE" => "single",
            "IBLOCK_TYPE" => "catalog",
            "LABEL_PROP_7" => array(
            ),
            "LABEL_PROP_MOBILE_7" => "",
            "LABEL_PROP_POSITION" => "top-left",
            "MESS_BTN_ADD_TO_BASKET" => "В корзину",
            "MESS_BTN_BUY" => "Купить",
            "MESS_BTN_DETAIL" => "Подробнее",
            "MESS_BTN_SUBSCRIBE" => "Подписаться",
            "MESS_NOT_AVAILABLE" => "Нет в наличии",
            "OFFER_TREE_PROPS_9" => "",
            "PAGE_ELEMENT_COUNT" => "9",
            "PARTIAL_PRODUCT_PROPERTIES" => "N",
            "PRICE_CODE" => array(
                0 => PRICE_BASE__CODE
            ),
            "PRICE_VAT_INCLUDE" => "Y",
            "PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
            "PRODUCT_ID_VARIABLE" => "id",
            "PRODUCT_PROPS_VARIABLE" => "prop",
            "PRODUCT_QUANTITY_VARIABLE" => "quantity",
            "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
            "PRODUCT_SUBSCRIPTION" => "N",
            'PROPERTY_CODE_'.IBLOCK_ID__CATALOG => array('NEW'),
            'PROPERTY_CODE_'.IBLOCK_ID__CATALOG_TP => array('COLOR'),
            "SECTION_CODE" => "",
            "SECTION_ELEMENT_CODE" => "",
            "SECTION_ELEMENT_ID" => $GLOBALS["CATALOG_CURRENT_ELEMENT_ID"],
            "SECTION_ID" => $GLOBALS["CATALOG_CURRENT_SECTION_ID"],
            "SHOW_CLOSE_POPUP" => "N",
            "SHOW_DISCOUNT_PERCENT" => "N",
            "SHOW_FROM_SECTION" => "N",
            "SHOW_MAX_QUANTITY" => "N",
            "SHOW_OLD_PRICE" => "N",
            "SHOW_PRICE_COUNT" => "1",
            "SHOW_SLIDER" => "N",
            "SLIDER_INTERVAL" => "3000",
            "SLIDER_PROGRESS" => "N",
            "TEMPLATE_THEME" => "blue",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "USE_PRICE_COUNT" => "N",
            "USE_PRODUCT_QUANTITY" => "N",
            "COMPONENT_TEMPLATE" => ".default",
            "PROPERTY_CODE_7" => array(
                0 => "",
                1 => "",
            ),
            "PROPERTY_CODE_MOBILE_7" => array(
            ),
            "PROPERTY_CODE_17" => array(
                0 => "COLOR",
                1 => "",
            ),
            "CART_PROPERTIES_17" => array(
                0 => "COLOR",
                1 => "",
            ),
            "ADDITIONAL_PICT_PROP_17" => "-",
            "OFFER_TREE_PROPS_17" => array(
                0 => "COLOR",
            )
        ),
        false
    );?>
</div>